/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cpy_ffmpegdemo_JNI */

#ifndef _Included_com_example_cpy_ffmpegdemo_JNI
#define _Included_com_example_cpy_ffmpegdemo_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cpy_ffmpegdemo_JNI
 * Method:    splitPCMFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_cpy_ffmpegdemo_JNI_splitPCMFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
